version: '3.9'
services:
  app:
    depends_on:
      - postgres
    build:
      context: ./app
      dockerfile: Dockerfile
    image: django-k8s:v1 # image name
    container_name: django_k8s_app
    env_file:
      - ./app/.env
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    # volumes:
    #   - staticfiles:/app/staticfiles/
  postgres:
    container_name: django_k8s_db
    image: postgres
    restart: always
    command: -p 5432
    env_file:
      - ./app/.env
    expose: # expose ports to services on the same network
      - 5432 
    ports: # internal ports for host machine interact with
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  # staticfiles:
  #   external: True 
  postgres_data: