name: Build Docker Container & Push to Digital Ocean Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  test_django_job:
    uses: mokom/django_kubernetes/.github/workflows/test-django.yaml@master
  docker_build_job:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: test-key-not-good-make-one-better
    steps:
    - uses: actions/checkout@v3
    
